// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiSolSMTRepo;

namespace WiSolSMTRepo.Migrations
{
    [DbContext(typeof(SMTDbContext))]
    partial class SMTDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("WiSolSMTRepo.Model.LineInfo", b =>
                {
                    b.Property<int>("LineInfoID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Is_active");

                    b.Property<string>("Name");

                    b.HasKey("LineInfoID");

                    b.ToTable("LineInfos");

                    b.HasData(
                        new
                        {
                            LineInfoID = 1,
                            Is_active = false,
                            Name = "SMT-A"
                        },
                        new
                        {
                            LineInfoID = 2,
                            Is_active = false,
                            Name = "SMT-B"
                        },
                        new
                        {
                            LineInfoID = 3,
                            Is_active = false,
                            Name = "SMT-C"
                        },
                        new
                        {
                            LineInfoID = 4,
                            Is_active = false,
                            Name = "SMT-D"
                        },
                        new
                        {
                            LineInfoID = 5,
                            Is_active = false,
                            Name = "SMT-E"
                        },
                        new
                        {
                            LineInfoID = 6,
                            Is_active = false,
                            Name = "SMT-F"
                        },
                        new
                        {
                            LineInfoID = 7,
                            Is_active = false,
                            Name = "SMT-G"
                        },
                        new
                        {
                            LineInfoID = 8,
                            Is_active = false,
                            Name = "SMT-H"
                        },
                        new
                        {
                            LineInfoID = 9,
                            Is_active = false,
                            Name = "SMT-I"
                        });
                });

            modelBuilder.Entity("WiSolSMTRepo.Model.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<DateTime>("ConfirmedTime");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<bool>("IsConfirmed");

                    b.Property<int>("LineInfoID");

                    b.Property<int>("OrderStatus");

                    b.Property<int>("PlanInfoID");

                    b.Property<int>("ProductID");

                    b.Property<int>("Reason");

                    b.Property<int>("StopDuration");

                    b.HasKey("OrderID");

                    b.HasIndex("LineInfoID");

                    b.HasIndex("PlanInfoID");

                    b.HasIndex("ProductID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WiSolSMTRepo.Model.PlanInfo", b =>
                {
                    b.Property<int>("PlanInfoID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<int>("Elapsed");

                    b.Property<DateTime>("FinishedTime");

                    b.Property<bool>("IsComplete");

                    b.Property<int>("LineInfoID");

                    b.Property<int>("Order");

                    b.Property<int>("ProductID");

                    b.Property<int>("Remain");

                    b.HasKey("PlanInfoID");

                    b.HasIndex("LineInfoID");

                    b.HasIndex("ProductID");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("WiSolSMTRepo.Model.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Name = "L7E0"
                        },
                        new
                        {
                            ProductID = 2,
                            Name = "L7E1"
                        });
                });

            modelBuilder.Entity("WiSolSMTRepo.Model.Order", b =>
                {
                    b.HasOne("WiSolSMTRepo.Model.LineInfo", "LineInfo")
                        .WithMany()
                        .HasForeignKey("LineInfoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WiSolSMTRepo.Model.PlanInfo", "PlanInfo")
                        .WithMany("Orders")
                        .HasForeignKey("PlanInfoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WiSolSMTRepo.Model.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WiSolSMTRepo.Model.PlanInfo", b =>
                {
                    b.HasOne("WiSolSMTRepo.Model.LineInfo", "Line")
                        .WithMany()
                        .HasForeignKey("LineInfoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WiSolSMTRepo.Model.Product", "Product")
                        .WithMany("PlanInfos")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
